let lanuage = [];
lanuage['en'] = {
    student: 'Student',
    hasRecive: 'has reviewed a lesson in your course',
    dateTimeFormat:'M/D/YYYY, hh:mm A',
    dateFormat:'M/D/YYYY',
    Webinar:'Webinar',
    Course:'Course',
    RemindRenewMemberShip:'Your membership will expire on ',
    RemindRenewMemberShipExpire:'Your membership expired on ',
    RemindRenewMemberShipMore:'Please renew to be continue',
    RemindMemberShipWebinar:'have started !',
    RemindMemberShipCourse:'have started !',
    RemindMemberShipWebinarDay:'will start in tomorrow!',
    RemindMemberShipCourseDay:'will start in tomorrow!',
    RemindMemberShipWebinarHour:'up coming.',
    RemindMemberShipCourseHour:'up coming.',
    liveTicket:', webinar have started ! ',
    RemindWebinar:'The webinar you have joined is up coming',
    RemindWebinarAuthor: 'Your upcoming webinar is now starting. Click here to start the webinar',
    RemindWebinarBefore24h: 'Tomorrow, you have a webinar. Click here for details',
    RemindWebinarAuthorBefore24h: 'Tomorrow, your webinar will begin. Click here for details',
    followTicket:" has created a seminar!",
    RemindScheduleAuthorBefore24h:'Tomorrow your course will be a one-day class',
    RemindScheduleBefore24h:'Tomorrow your course will be a one-day class',
    interactWebinar:' have interacted your webinar',
    userSentTicket:'have bought ticket in your webinar',
    userBuyTicket:'You have bought successfully ticket of webinar',
    RejectCourse:'Your course have rejected',
    joinCoursesToAuthor:'Your course has 1 new member',
    inviteLiveLesson:' Your lesson have started',
    AuthorCourses:'You have successfully created the course!',
    InviteCourses:' has invited you to join the course!',
    RemindScheduleAuthor: 'Your course will take place in 30 minutes!',
    RemindSchedule : 'Your course is about to take off !',
    LiveScheduleStream: ' live streaming schedule',
    inviteLivestream:' invited you in live stream!',
    followLivestream:' live streaming',
    ScheduleStreamInvite:' invited you in schedule',
    ScheduleStream:' has created a schedule',
    followCourses:' has created a course',
    joinCourses: 'You have enrolled successfully',
    inviteStream:" invite live stream",
    streaming: " live streaming",
    anonymous: 'Anonymous',
    somebody: 'Somebody',
    follow: ' started following you.',
    appointment: ' made an appointment with you.',
    appointmentComment: ' updated the appointment',
    upvoteKnowledge: ' upvoted your knowledge ',
    VoteAnswerToAuthorAnswer: ' upvoted your answer',
    answerQuestionUserVote: ' answered a question that you upvoted ',
    answerQuestionUserAnswer: ' added an answer to the question ',
    answerQuestionAuthor: ' answered your question ',
    answerReplyQuestionAuthor: ' replied to a question ',
    answerReplyQuestionUserVote: ' added a reply to your answer ',
    answerReplyQuestionUserReply: ' replied on an answer your replied on a question ',
    replyQuestionAnswer: ' replied to your answer to the question ',
    upVoteQuestion: ' upvoted your question ',
    censorKnowledge: 'Your knowledge has been approved! Check it out ',
    rejectKnowledge: 'Your knowledge has been rejected. Click here to review & edit ',
    deleteKnowledge: 'Your knowledge has been deleted, ',
    approvedExpert: 'Congratulations! You officially become a teacher on Tesse. Let\'s celebrate and wait for your first class.',
    completeExpert: 'You have completed the application to become a teacher on Tesse. Please wait until our recruitment team contacts you for the next step.',
    rejectExpert: 'Sorry! You can not become a teacher on Tesse now. Let\'s try at another time.',
    userInviteCode: ' just used your invite code. When ',
    userInviteCode1: ' makes a call you will both get $2 Tesse credit.',
    userInvited: 'Congratulations! You earned $2 Tesse credit. ',
    userInvited1: ' has completed a call.',
    userUsedInvited: 'Congratulations! You earned $2 Tesse credit.',
    approveSuggestSkill: 'Your suggested skill has been approved ',
    rejectSuggestSkill: 'Your suggested skill has been rejected ',
    commentKnowledgeAuthor: ' commented on your knowledge ',
    commentKnowledgeUserVote: ' commented on a knowledge that you upvoted ',
    unsetExpert: 'Your expert profile has been canceled.',
    commentKnowledgeUserComment: ' replied to your comment ',
    commentReplyKnowledgeAuthor: ' replied to a comment on your knowledge ',
    commentReplyKnowledgeComment: ' replied to a comment that you\'re commented ',
    memberShip: 'Congratulations! You registered membership. Membership will expire on ',
    renewalMemberShip: 'Congratulations! You renewed membership. Membership will expire on ',
    adminActive: 'Your membership account added',
    adminActiveMore: 'date. Membership will expire on ',
    memberShipSenderInvite: 'Congratulations! You received membership',
    memberShipSenderInviteMore: 'from the promotion "Buy 1 month, study all year" on Tesse',
    memberShipReceiverInvite: 'Congratulations! You received membership',
    memberShipReceiverInviteMore: 'from the promotion "Buy 1 month, study all year" on Tesse',
};
lanuage['vi'] = {
    student: 'Học viên',
    hasRecive: 'đã đánh giá một buổi học trong khóa học',
    dateTimeFormat:'hh:mm A, D/M/YYYY',
    dateFormat:'D/M/YYYY',
    Webinar:'Hội thảo',
    Course:'Khóa học',
    RemindRenewMemberShip:'Membership của bạn trên Tesse Inc sẽ hết hạn lúc ',
    RemindRenewMemberShipExpire:'Membership của bạn trên Tesse đã hết hạn lúc ',
    RemindRenewMemberShipMore:'Hãy gia hạn ngay hôm nay để tiếp tục',
    RemindMemberShipWebinar:'đã bắt đầu!',
    RemindMemberShipCourse:'đã bắt đầu!',
    RemindMemberShipWebinarDay:'sẽ bắt đầu vào ngày mai!',
    RemindMemberShipCourseDay:'sẽ bắt đầu vào ngày mai!',
    RemindMemberShipWebinarHour:'sắp diễn ra.',
    RemindMemberShipCourseHour:'sắp diễn ra.',
    liveTicket:', hội thảo bạn tham gia đã bắt đầu! ',
    RemindWebinar:'Hội thảo bạn đã tham gia sắp bắt đầu!',
    RemindWebinarAuthor: 'Hội thảo của bạn sắp bắt đầu. Vui lòng click vào đây để tiến hành chuẩn bị',
    RemindWebinarBefore24h: 'Ngày mai, bạn có một hội thảo. Click vào đây để xem chi tiết',
    RemindWebinarAuthorBefore24h: 'Ngày mai, hội thảo của bạn sẽ bắt đầu. Click vào đây để xem chi t',
    followTicket:" đã tạo một hội thảo!",
    RemindScheduleAuthorBefore24h:'Ngày mai khóa học của bạn sẽ có một buổi học',
    RemindScheduleBefore24h:'Ngày mai khóa học của bạn sẽ có một buổi học',
    interactWebinar:' đã tương tác vào hội thảo của bạn',
    userSentTicket:'đã mua thành công vé về hội thảo ',
    userBuyTicket:'Bạn đã mua thành công vé cho hội thảo',
    RejectCourse:'Khóa học của bạn đã bị từ chối',
    inviteStream:" mời bạn xem trực tiếp!",
    streaming:' đang phát trực tiếp.',
    joinCoursesToAuthor:'Khóa học của bạn đã có thêm 1 thành viên mới',
    AuthorCourses:'Bạn đã tạo thành công khóa học',
    inviteLiveLesson:' Buổi học của bạn đã bắt đầu',
    InviteCourses:' đã mời bạn tham gia khóa học!',
    RemindScheduleAuthor:'Khóa học của bạn sẽ diễn ra sau 30 phút nữa!',
    RemindSchedule:'Khóa học của bạn sắp diễn ra !',
    LiveScheduleStream:' đang trực tiếp!',
    followCourses:' đã tạo 1 khóa học mới',
    joinCourses: 'Bạn đã đăng ký tham gia thành công khóa học',
    inviteLivestream:' mời bạn xem live stream!',
    followLivestream:' đang phát trực tiếp!',
    ScheduleStreamInvite:' đã thêm bạn vào 1 dự định live stream!',
    ScheduleStream:' đã tạo 1 dự định live stream',
    anonymous: 'Người ẩn danh',
    somebody: 'Ai đó',
    follow: ' Đã theo dõi bạn.',
    appointment: ' đã đặt một cuộc hẹn với bạn.',
    appointmentComment: ' đã cập nhập một cuộc hẹn',
    upvoteKnowledge: ' upvoted bài viết của bạn ',
    answerQuestionUserVote: ' trả lời một câu hỏi bạn đã upvoted ',
    VoteAnswerToAuthorAnswer: ' đã upvoted câu trả lời của bạn ',
    answerQuestionUserAnswer: ' thêm một câu trả lời vào câu hỏi ',
    answerQuestionAuthor: ' đã trả lời câu hỏi của bạn ',
    answerReplyQuestionAuthor: ' trả lời câu hỏi ',
    answerReplyQuestionUserVote: ' đã thêm một câu trả lời vào câu hỏi ',
    answerReplyQuestionUserReply: ' đã phản hồi câu trả lời của bạn ',
    replyQuestionAnswer: ' đã phản hồi câu trả lời của bạn ',
    upVoteQuestion: ' đã upvoted câu hỏi của bạn ',
    censorKnowledge: 'Bài viết của bạn đã được duyệt ',
    rejectKnowledge: 'Bài viết của bạn đã bị từ chối. Nhấp vào đây để xem lại & chỉnh sửa nó ',
    deleteKnowledge: 'Bài viết của bạn đã bị xóa ',
    approvedExpert: 'Chúc mừng! Bạn đã chính thức trở thành giáo viên trên Tesse. Hãy chờ đợi lớp đầu tiên của mình được mở.',
    completeExpert: 'Bạn đã ứng tuyển trở thành giáo viên trên Tesse. Vui lòng chờ đợi đội ngũ tuyển dụng giáo viên liên hệ cho bước tiếp theo.',
    rejectExpert: 'Xin lỗi! Bạn chưa thể trở thành giáo viên trên Tesse. Hãy ứng tuyển lại vào lần khác.',
    userInviteCode: ' vừa sử dụng mã của bạn. Khi ',
    userInviteCode1: ' thực hiện một cuộc gọi để nhận $2 từ Tesse.',
    userInvited: 'Xin chúc mừng! Bạn kiếm được $2 từ Tesse. ',
    userInvited1: ' đã hoàn thành một cuộc gọi.',
    userUsedInvited: 'Xin chúc mừng! Bạn kiếm được $2 từ Tesse.',
    approveSuggestSkill: 'Kỹ năng đề xuất của bạn đã được duyệt ',
    rejectSuggestSkill: 'Kỹ năng đề xuất của bạn đã bị từ chối ',
    commentKnowledgeAuthor: ' đã trả lời vào bài viết của bạn ',
    commentKnowledgeUserVote: ' đã trả lời vào bài viết bạn đã upvoted ',
    unsetExpert: 'Tài khoản chuyên gia của bạn đã bị hủy.',
    commentKnowledgeUserComment: ' đã phản hồi vào câu trả lời của bạn ',
    commentReplyKnowledgeAuthor: ' đã phản hồi vào câu trả lời trên bài viết của bạn ',
    commentReplyKnowledgeComment: ' đã phản hồi vào câu trả lời trên bài viết ',
    memberShip: 'Chúc mừng, bạn đã đăng ký membership thành công. Membership được đăng ký đến ',
    renewalMemberShip: 'Chúc mừng, bạn đã gia hạn membership thành công. Membership được gia hạn đến ',
    adminActive: 'Membership được cộng thêm',
    adminActiveMore: 'ngày. Membership được gia hạn đến',
    memberShipSenderInvite: 'Chúc mừng, Bạn đã nhận được gói membership',
    memberShipSenderInviteMore: 'từ chương trình "Mua 1 tháng, học cả năm" trên Tesse. Membership được tính đến ',
    memberShipReceiverInvite: 'Chúc mừng, Bạn đã nhận được gói membership',
    memberShipReceiverInviteMore: 'từ chương trình "Mua 1 tháng, học cả năm" trên Tesse. Membership được tính đến ',

}

export default lanuage;
